[package]
name = "steel5"
version = "0.1.0"
authors = ["Arthur Mendes <arthurmco@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive = "~0.3"
num-traits = "0.2"